- name: Deploy the application
  hosts: tag_Name_openAFRICA_main_4
  #hosts: tag_openafricastaging_openafricastaging 
  remote_user: ubuntu
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/ubuntu.yml

  roles:
    - deploy
