- name: Deploy the application
  hosts: tag_role_africaopendata
  sudo: yes
  sudo_user: root
  remote_user: ubuntu
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/ubuntu.yml

  roles:
    - deploy
